eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/

server:
  port: 8883

spring:
  application:
    name: mental-auth
  redis:
    database: 1
    host: localhost
    port: 6379
    pool:
      max-active: 20
    password: 123456
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mental_auth?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

feign:
  hystrix:
    enabled: true #Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：

jwt:
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45

client:
  id: mental-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis:
  basepackage: com.emed.mental.auth.server.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

logging:
  level:
    com:
      emed:
        mental:
          auth:
            admin:
              mapper: trace